development:
  clients:
    default:
      database: tourneysite_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: tourneysite_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: tourneysite_prod
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
